
BEGIN_EVENT_TABLE(treesheets::Frame, wxFrame)
  #ifndef __WXMAC__
    EVT_DPI_CHANGED(treesheets::Frame::OnDPIChanged)
  #endif
  EVT_SIZING(treesheets::Frame::OnSizing)
  EVT_MENU(wxID_ANY, treesheets::Frame::OnMenu)
  EVT_TEXT(A_SEARCH, treesheets::Frame::OnSearch)
  EVT_TEXT_ENTER(A_SEARCH, treesheets::Frame::OnSearchReplaceEnter)
  EVT_TEXT_ENTER(A_REPLACE, treesheets::Frame::OnSearchReplaceEnter)
  EVT_CLOSE(treesheets::Frame::OnClosing)
  EVT_MAXIMIZE(treesheets::Frame::OnMaximize)
  EVT_ACTIVATE_APP(treesheets::Frame::OnActivate)
  EVT_COMBOBOX(A_CELLCOLOR, treesheets::Frame::OnChangeColor)
  EVT_COMBOBOX(A_TEXTCOLOR, treesheets::Frame::OnChangeColor)
  EVT_COMBOBOX(A_BORDCOLOR, treesheets::Frame::OnChangeColor)
  EVT_COMBOBOX(A_DDIMAGE,   treesheets::Frame::OnDDImage)
  EVT_ICONIZE(treesheets::Frame::OnIconize)
  EVT_AUINOTEBOOK_PAGE_CHANGED(wxID_ANY, treesheets::Frame::OnTabChange)
  EVT_AUINOTEBOOK_PAGE_CLOSE(wxID_ANY, treesheets::Frame::OnTabClose)
  EVT_SYS_COLOUR_CHANGED(treesheets::Frame::OnSysColourChanged)
END_EVENT_TABLE()

BEGIN_EVENT_TABLE(treesheets::App, wxApp)
END_EVENT_TABLE()

BEGIN_EVENT_TABLE(treesheets::Canvas, wxScrolledWindow)
  EVT_MOUSEWHEEL(treesheets::Canvas::OnMouseWheel)
  EVT_PAINT(treesheets::Canvas::OnPaint)
  EVT_MOTION(treesheets::Canvas::OnMotion)
  EVT_LEFT_DOWN(treesheets::Canvas::OnLeftDown)
  EVT_LEFT_UP(treesheets::Canvas::OnLeftUp)
  EVT_RIGHT_DOWN(treesheets::Canvas::OnRightDown)
  EVT_LEFT_DCLICK(treesheets::Canvas::OnLeftDoubleClick)
  EVT_CHAR(treesheets::Canvas::OnChar)
  EVT_KEY_DOWN(treesheets::Canvas::OnKeyDown)
  EVT_CONTEXT_MENU(treesheets::Canvas::OnContextMenuClick)
  EVT_SIZE(treesheets::Canvas::OnSize)
  EVT_SCROLLWIN(treesheets::Canvas::OnScrollWin)
END_EVENT_TABLE()

BEGIN_EVENT_TABLE(treesheets::ThreeChoiceDialog, wxDialog)
    EVT_BUTTON(wxID_ANY, treesheets::ThreeChoiceDialog::OnButton)
END_EVENT_TABLE()

BEGIN_EVENT_TABLE(treesheets::DateTimeRangeDialog, wxDialog)
    EVT_BUTTON(wxID_ANY, treesheets::DateTimeRangeDialog::OnButton)
END_EVENT_TABLE()
