BEGIN_EVENT_TABLE(treesheets::TSFrame, wxFrame)
  EVT_DPI_CHANGED(treesheets::TSFrame::OnDPIChanged)
  EVT_SIZING(treesheets::TSFrame::OnSizing)
  EVT_MENU(wxID_ANY, treesheets::TSFrame::OnMenu)
  EVT_TEXT(A_SEARCH, treesheets::TSFrame::OnSearch)
  EVT_TEXT_ENTER(A_SEARCH, treesheets::TSFrame::OnSearchReplaceEnter)
  EVT_TEXT_ENTER(A_REPLACE, treesheets::TSFrame::OnSearchReplaceEnter)
  EVT_CLOSE(treesheets::TSFrame::OnClosing)
  EVT_MAXIMIZE(treesheets::TSFrame::OnMaximize)
  EVT_ACTIVATE_APP(treesheets::TSFrame::OnActivate)
  EVT_COMBOBOX(A_CELLCOLOR, treesheets::TSFrame::OnChangeColor)
  EVT_COMBOBOX(A_TEXTCOLOR, treesheets::TSFrame::OnChangeColor)
  EVT_COMBOBOX(A_BORDCOLOR, treesheets::TSFrame::OnChangeColor)
  EVT_COMBOBOX(A_DDIMAGE,   treesheets::TSFrame::OnDDImage)
  EVT_ICONIZE(treesheets::TSFrame::OnIconize)
  EVT_AUINOTEBOOK_PAGE_CHANGED(wxID_ANY, treesheets::TSFrame::OnTabChange)
  EVT_AUINOTEBOOK_PAGE_CLOSE(wxID_ANY, treesheets::TSFrame::OnTabClose)
  EVT_SYS_COLOUR_CHANGED(treesheets::TSFrame::OnSysColourChanged)
  EVT_COMMAND(wxID_ANY, UPDATE_STATUSBAR_REQUEST, treesheets::TSFrame::OnUpdateStatusBarRequest)
END_EVENT_TABLE()

BEGIN_EVENT_TABLE(treesheets::TSApp, wxApp)
END_EVENT_TABLE()

BEGIN_EVENT_TABLE(treesheets::TSCanvas, wxScrolledWindow)
  EVT_MOUSEWHEEL(treesheets::TSCanvas::OnMouseWheel)
  EVT_PAINT(treesheets::TSCanvas::OnPaint)
  EVT_MOTION(treesheets::TSCanvas::OnMotion)
  EVT_LEFT_DOWN(treesheets::TSCanvas::OnLeftDown)
  EVT_LEFT_UP(treesheets::TSCanvas::OnLeftUp)
  EVT_RIGHT_DOWN(treesheets::TSCanvas::OnRightDown)
  EVT_LEFT_DCLICK(treesheets::TSCanvas::OnLeftDoubleClick)
  EVT_CHAR(treesheets::TSCanvas::OnChar)
  EVT_KEY_DOWN(treesheets::TSCanvas::OnKeyDown)
  EVT_CONTEXT_MENU(treesheets::TSCanvas::OnContextMenuClick)
  EVT_SIZE(treesheets::TSCanvas::OnSize)
  EVT_SCROLLWIN(treesheets::TSCanvas::OnScrollWin)
  #ifdef __WXMAC__
    EVT_COMMAND(wxID_ANY, SCROLLTOSELECTION_REQUEST, treesheets::TSCanvas::OnScrollToSelectionRequest)
  #endif  
END_EVENT_TABLE()

BEGIN_EVENT_TABLE(treesheets::ThreeChoiceDialog, wxDialog)
    EVT_BUTTON(wxID_ANY, treesheets::ThreeChoiceDialog::OnButton)
END_EVENT_TABLE()

BEGIN_EVENT_TABLE(treesheets::DateTimeRangeDialog, wxDialog)
    EVT_BUTTON(wxID_ANY, treesheets::DateTimeRangeDialog::OnButton)
END_EVENT_TABLE()
