# Compiles the PNG and SVG files below IMAGES_DIR into a C++ header, so they need not be
# installed alongside the executable. Each image is looked up by its path relative to IMAGES_DIR.
# Usage: cmake -DIMAGES_DIR=<TS/images> -DOUTPUT=<header> -P <this file>

file(GLOB_RECURSE images RELATIVE "${IMAGES_DIR}" "${IMAGES_DIR}/*.png" "${IMAGES_DIR}/*.svg")
list(SORT images)

# CMake regular expressions lack repetition counts, so spell out 20 bytes per line
string(REPEAT "0x..," 20 line)

set(arrays "")
set(entries "")
set(index 0)
foreach(image IN LISTS images)
    file(READ "${IMAGES_DIR}/${image}" hex HEX)
    string(LENGTH "${hex}" hexlength)
    math(EXPR size "${hexlength} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "(${line})" "\\1\n    " bytes "${bytes}")
    string(APPEND arrays "static const unsigned char embedded_image_${index}[] = {\n    ${bytes}\n};\n")
    string(APPEND entries "    {\"${image}\", embedded_image_${index}, ${size}},\n")
    math(EXPR index "${index} + 1")
endforeach()

set(content "// Generated by cmake/EmbedImages.cmake from TS/images, do not edit.

#pragma once

struct EmbeddedImage {
    const char *name;
    const unsigned char *data;
    size_t size;
};

${arrays}
static const EmbeddedImage embedded_images[] = {
${entries}};
")

# Only touch the header when it changes, so that it does not trigger needless recompiles.
file(CONFIGURE OUTPUT "${OUTPUT}" CONTENT "${content}" @ONLY)
