# Compiles data files into the executable, so they need not be installed alongside it.
#
# treesheets_embed_files(<name> <dir> <globs>...) generates the header embedded_<name>.h with the
# array embedded_<name> of EmbeddedFile (see src/main.cpp), holding the files matching the globs
# below <dir>, each named by its path relative to <dir>.

if(CMAKE_SCRIPT_MODE_FILE)
    # Generation step, run at build time:
    # cmake -DNAME=<name> -DDIR=<dir> -DLIST=<file list> -DOUTPUT=<header> -P <this file>
    file(STRINGS "${LIST}" files)

    # CMake regular expressions lack repetition counts, so spell out 20 bytes per line
    string(REPEAT "0x..," 20 line)

    set(arrays "")
    set(entries "")
    set(index 0)
    foreach(file IN LISTS files)
        cmake_path(RELATIVE_PATH file BASE_DIRECTORY "${DIR}" OUTPUT_VARIABLE relative)
        file(READ "${file}" hex HEX)
        string(LENGTH "${hex}" hexlength)
        math(EXPR size "${hexlength} / 2")
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
        string(REGEX REPLACE "(${line})" "\\1\n    " bytes "${bytes}")
        string(APPEND arrays "static const unsigned char embedded_${NAME}_${index}[] = {\n    ${bytes}\n};\n")
        string(APPEND entries "    {\"${relative}\", embedded_${NAME}_${index}, ${size}},\n")
        math(EXPR index "${index} + 1")
    endforeach()

    set(content "// Generated by cmake/EmbedFiles.cmake from ${DIR}, do not edit.

#pragma once

${arrays}
static const EmbeddedFile embedded_${NAME}[] = {
${entries}};
")

    # Only touch the header when it changes, so that it does not trigger needless recompiles.
    file(CONFIGURE OUTPUT "${OUTPUT}" CONTENT "${content}" @ONLY)
    return()
endif()

function(treesheets_embed_files name dir)
    set(globs "")
    foreach(glob IN LISTS ARGN)
        list(APPEND globs "${dir}/${glob}")
    endforeach()
    file(GLOB_RECURSE files CONFIGURE_DEPENDS ${globs})
    list(SORT files)

    set(generated_dir "${CMAKE_CURRENT_BINARY_DIR}/generated")
    set(header "${generated_dir}/embedded_${name}.h")
    # Record the list of files, so that removing one regenerates the header as well
    set(list_file "${generated_dir}/embedded_${name}.txt")
    list(JOIN files "\n" list_content)
    file(CONFIGURE OUTPUT "${list_file}" CONTENT "${list_content}\n")

    add_custom_command(
        OUTPUT "${header}"
        COMMAND ${CMAKE_COMMAND}
            "-DNAME=${name}" "-DDIR=${dir}" "-DLIST=${list_file}" "-DOUTPUT=${header}"
            -P "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
        DEPENDS ${files} "${list_file}" "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
        COMMENT "Embedding ${name}"
        VERBATIM
    )
    target_sources(TreeSheets PRIVATE "${header}")
    target_include_directories(TreeSheets PRIVATE "${generated_dir}")
endfunction()
